import logging
import secrets

from datetime import timedelta

import requests

from odoo import api, fields, models

_logger = logging.getLogger(__name__)

PAIRING_TOKEN_PARAM = 'dooprint.pairing_token'
# Without a heartbeat for this long, a device is considered offline. It beats every 30 s.
ONLINE_MINUTES = 2


class DooprintDevice(models.Model):
    """A computer running dooprint, paired with this database, with the printers it reports."""
    _name = 'dooprint.device'
    _description = 'Print Device'
    _order = 'name'

    name = fields.Char(string='Name', required=True)
    active = fields.Boolean(string='Active', default=True)
    company_id = fields.Many2one('res.company', string='Company', default=lambda self: self.env.company)
    identifier = fields.Char(string='Identifier', required=True, readonly=True, index=True, copy=False,
        help="Generated by the device on first start. It never changes.")
    token = fields.Char(string='Token', readonly=True, copy=False, groups='base.group_system',
        help="Credential the device uses to fetch its jobs. Issued when pairing.")
    paired = fields.Boolean(string='Paired', compute='_compute_paired', store=True)
    mode = fields.Selection([
        ('agent', 'Agent'),
        ('local', 'Local'),
    ], string='Mode', required=True, default='agent', readonly=True,
        help="Agent: the device picks up its jobs; works with Odoo outside its network.\n"
             "Local: Odoo sends the jobs; only when the device is on Odoo's network.")
    address = fields.Char(string='Address', readonly=True,
        help="Address of its print server as the device sees itself. In local mode Odoo sends jobs here.")
    version = fields.Char(string='Version', readonly=True)
    os = fields.Selection([
        ('linux', 'Linux'),
        ('windows', 'Windows'),
        ('darwin', 'macOS'),
    ], string='Operating System', readonly=True)
    paired_at = fields.Datetime(string='Paired On', readonly=True)
    last_seen = fields.Datetime(string='Last Seen', readonly=True)
    state = fields.Selection([
        ('online', 'Online'),
        ('offline', 'Offline'),
        ('revoked', 'Unpaired'),
    ], string='Status', compute='_compute_state', search='_search_state')

    printer_ids = fields.One2many('dooprint.printer', 'device_id', string='Printers')
    job_ids = fields.One2many('dooprint.job', 'device_id', string='Jobs')
    command_ids = fields.One2many('dooprint.command', 'device_id', string='Commands')
    printer_count = fields.Integer(string='Printer Count', compute='_compute_counts')
    connected_printer_count = fields.Integer(string='Connected Printers', compute='_compute_counts')
    pending_job_count = fields.Integer(string='Pending Jobs', compute='_compute_counts')
    failed_job_count = fields.Integer(string='Failed Jobs (24 h)', compute='_compute_counts')
    command_count = fields.Integer(string='Command Count', compute='_compute_counts')

    _sql_constraints = [
        ('identifier_unique', 'UNIQUE(identifier)', "This device is already registered."),
        ('token_unique', 'UNIQUE(token)', "The device token must be unique."),
    ]

    @api.depends('token')
    def _compute_paired(self):
        for device in self.sudo():
            device.paired = bool(device.token)

    @api.depends('last_seen', 'paired')
    def _compute_state(self):
        limit = fields.Datetime.now() - timedelta(minutes=ONLINE_MINUTES)
        for device in self:
            if not device.paired:
                device.state = 'revoked'
            elif device.last_seen and device.last_seen >= limit:
                device.state = 'online'
            else:
                device.state = 'offline'

    def _search_state(self, operator, value):
        if operator not in ('=', 'in'):
            raise NotImplementedError(self.env._("The status can only be filtered by equality."))
        states = [value] if isinstance(value, str) else list(value)
        limit = fields.Datetime.now() - timedelta(minutes=ONLINE_MINUTES)
        domains = {
            'online': ['&', ('paired', '=', True), ('last_seen', '>=', limit)],
            'offline': ['&', ('paired', '=', True), '|', ('last_seen', '=', False), ('last_seen', '<', limit)],
            'revoked': [('paired', '=', False)],
        }
        domain = []
        for state in states:
            domain = ['|'] + domain + domains[state] if domain else domains[state]
        return domain or [('id', '=', False)]

    @api.depends('printer_ids.connected_status', 'job_ids.state', 'command_ids')
    def _compute_counts(self):
        since = fields.Datetime.now() - timedelta(hours=24)
        for device in self:
            device.printer_count = len(device.printer_ids)
            device.connected_printer_count = len(
                device.printer_ids.filtered(lambda printer: printer.connected_status == 'connected'))
            device.pending_job_count = len(device.job_ids.filtered(lambda job: job.state in ('queued', 'sent')))
            device.failed_job_count = len(device.job_ids.filtered(
                lambda job: job.state == 'failed' and job.create_date and job.create_date >= since))
            device.command_count = len(device.command_ids)

    # --- Pairing ----------------------------------------------------------------------------

    @api.model
    def _new_pairing_string(self):
        """Issue a new pairing token and return what the user pastes into the device: the Odoo
        address with the token, in one string. Opening the wizard again replaces the token."""
        token = secrets.token_hex(16)
        self.env['ir.config_parameter'].sudo().set_param(PAIRING_TOKEN_PARAM, token)
        return "%s?token=%s&db_name=%s" % (self.get_base_url(), token, self.env.cr.dbname)

    @api.model
    def _register_device(self, pairing_token, values, printers):
        """Pair a device with the current pairing token and return the device's own token.
        The pairing token is single use: it is cleared once a device uses it."""
        params = self.env['ir.config_parameter'].sudo()
        expected = params.get_param(PAIRING_TOKEN_PARAM)
        if not (pairing_token and expected and pairing_token == expected):
            return False
        identifier = values.get('identifier')
        if not identifier:
            return False

        device = self.with_context(active_test=False).search([('identifier', '=', identifier)], limit=1)
        written = self._reported_values(values)
        written.update({
            'name': values.get('name') or identifier,
            'token': secrets.token_urlsafe(24),
            'paired_at': fields.Datetime.now(),
            'last_seen': fields.Datetime.now(),
            'active': True,
        })
        if device:
            device.write(written)
        else:
            device = self.create(dict(written, identifier=identifier))
        params.set_param(PAIRING_TOKEN_PARAM, '')
        device._sync_printers(printers)
        return device.token

    @api.model
    def _reported_values(self, values):
        """What the device reports about itself, keeping only values the model knows."""
        reported = {}
        if values.get('mode') in ('agent', 'local'):
            reported['mode'] = values['mode']
        if values.get('os') in dict(self._fields['os'].selection):
            reported['os'] = values['os']
        for field in ('address', 'version'):
            if values.get(field):
                reported[field] = values[field]
        return reported

    def _heartbeat(self, values, printers):
        """Device heartbeat: refresh its data and its printer list."""
        self.ensure_one()
        self.write(dict(self._reported_values(values), last_seen=fields.Datetime.now()))
        self._sync_printers(printers)

    def _sync_printers(self, printers):
        """Register the printers the device reports; the missing ones are marked disconnected."""
        self.ensure_one()
        Printer = self.env['dooprint.printer']
        seen = Printer
        for reported in printers or []:
            identifier = reported.get('id')
            if not identifier:
                continue
            values = {
                'name': reported.get('name') or identifier,
                'printer_type': 'label' if reported.get('type') == 'label' else 'receipt',
                'connection': 'network' if reported.get('connection') == 'network' else 'usb',
                'ip_address': reported.get('ip') or False,
                'connected_status': 'connected',
            }
            printer = Printer.with_context(active_test=False).search(
                [('device_id', '=', self.id), ('identifier', '=', identifier)], limit=1)
            if printer:
                printer.write(values)
            else:
                printer = Printer.create(dict(values, device_id=self.id, identifier=identifier))
            seen |= printer
        (self.printer_ids - seen).write({'connected_status': 'disconnected'})

    def _notify(self):
        """Wake the device up through the bus so it fetches jobs without waiting for its next beat."""
        for device in self.sudo():
            if device.mode == 'agent' and device.token:
                self.env['bus.bus']._sendone(device.token, 'DOOPRINT_JOB', {'device': device.id})

    def _ping(self):
        """Check the device now instead of waiting for its next heartbeat.
        Agent: the bus wakes it up and it answers with a heartbeat within a second.
        Local: Odoo reaches its web interface and updates the last seen date if it answers."""
        for device in self.sudo().filtered('paired'):
            if device.mode == 'agent':
                device._notify()
                continue
            if not device.address:
                continue
            try:
                requests.get('http://%s/' % device.address, timeout=3).raise_for_status()
            except requests.RequestException as error:
                _logger.info("dooprint: device %s did not answer: %s", device.name, error)
                continue
            device.last_seen = fields.Datetime.now()

    def _http_request(self, url, method='GET', body=None, headers=None, origin=None):
        """Make an HTTP request from the device network, to reach equipment Odoo cannot see.
        Returns the dooprint.command; its result holds the status and the body of the answer.
        `origin` may implement _dooprint_command_done(command) to get the result."""
        self.ensure_one()
        payload = {'url': url, 'method': method.upper(), 'body': body or '', 'headers': headers or {}}
        return self.env['dooprint.command'].sudo()._send(self, 'http', payload=payload, origin=origin)

    # --- Actions ----------------------------------------------------------------------------

    @api.model
    def action_connect_device(self):
        """Open the connect wizard on a saved record, so its token is issued once."""
        return self.env['dooprint.pairing'].create({})._open()

    def action_open_homepage(self):
        """Open the web interface of the device."""
        self.ensure_one()
        return {'type': 'ir.actions.act_url', 'url': 'http://%s' % self.address, 'target': 'new'}

    def action_ping(self):
        """Called by the form when it opens, so the status shown is current."""
        self._ping()
        return True

    def action_restart(self):
        for device in self:
            self.env['dooprint.command']._send(device, 'restart')
        return self._notification(self.env._("Restart command sent."))

    def action_refresh_printers(self):
        for device in self:
            self.env['dooprint.command']._send(device, 'refresh')
        return self._notification(self.env._("The device will rescan its printers."))

    def action_revoke(self):
        """Invalidate the token: the device stops receiving jobs until it is paired again."""
        self.sudo().write({'token': False})
        return self._notification(self.env._("Device unpaired."), 'warning')

    def action_open_printers(self):
        self.ensure_one()
        action = self.env['ir.actions.act_window']._for_xml_id('dooprint.dooprint_printer_action')
        action.update(domain=[('device_id', '=', self.id)], context={'default_device_id': self.id})
        return action

    def action_open_jobs(self):
        self.ensure_one()
        action = self.env['ir.actions.act_window']._for_xml_id('dooprint.dooprint_job_action')
        action.update(domain=[('device_id', '=', self.id)], context={'search_default_pending': 1})
        return action

    def action_open_failed_jobs(self):
        self.ensure_one()
        action = self.env['ir.actions.act_window']._for_xml_id('dooprint.dooprint_job_action')
        action.update(domain=[('device_id', '=', self.id)], context={'search_default_failed': 1})
        return action

    def action_open_commands(self):
        self.ensure_one()
        action = self.env['ir.actions.act_window']._for_xml_id('dooprint.dooprint_command_action')
        action.update(domain=[('device_id', '=', self.id)])
        return action

    @api.model
    def _notification(self, message, kind='success'):
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {'type': kind, 'message': message, 'next': {'type': 'ir.actions.act_window_close'}},
        }
